"""Customer screens (mixin for App)."""
import tkinter as tk
from tkinter import ttk, messagebox

import customers as customer_db
import receipts as receipt_db

from ui_common import make_sortable


class CustomersMixin:
    def show_customers(self):
        self.current_view = "customers"
        self._clear_container()

        header = ttk.Frame(self.container)
        header.pack(fill="x", pady=(0, 10))
        ttk.Label(header, text="Customers", font=("Segoe UI", 20, "bold")).pack(side="left")

        bar = ttk.Frame(self.container)
        bar.pack(fill="x", pady=(0, 10))
        bar.columnconfigure(1, weight=1)
        search_term = tk.StringVar()
        ttk.Label(bar, text="Search:").grid(row=0, column=0, sticky="w")
        search_entry = ttk.Entry(bar, textvariable=search_term)
        search_entry.grid(row=0, column=1, sticky="ew", padx=(8, 10))
        search_entry.focus_set()
        search_entry.bind("<Return>", lambda e: do_search())
        ttk.Button(bar, text="Search", command=lambda: do_search()).grid(row=0, column=2, padx=(0, 8))
        ttk.Button(bar, text="Clear", command=lambda: clear()).grid(row=0, column=3)

        columns = ("name", "account_number", "contact", "email", "phone")
        headings = ("Name", "Account #", "Contact", "Email", "Phone")
        table_frame = ttk.Frame(self.container)
        table_frame.pack(fill="both", expand=True)
        tree = ttk.Treeview(table_frame, columns=columns, show="headings")
        sb = ttk.Scrollbar(table_frame, orient="vertical", command=tree.yview)
        tree.configure(yscrollcommand=sb.set)
        sb.pack(side="right", fill="y")
        tree.pack(side="left", fill="both", expand=True)
        for col, heading in zip(columns, headings):
            tree.heading(col, text=heading)
            tree.column(col, width=140)
        make_sortable(tree)

        status_label = ttk.Label(self.container, text="")
        status_label.pack(anchor="w", pady=(8, 0))

        def refresh():
            query = search_term.get().strip().lower()
            tree.delete(*tree.get_children())
            for c in customer_db.get_all_customers():
                if not query or query in (c["name"] or "").lower():
                    tree.insert(
                        "", "end", iid=str(c["id"]),
                        values=(c["name"], c["account_number"], c["contact"], c["email"], c["phone"]),
                    )
            if not tree.get_children():
                status_label.config(
                    text="No customers match the search." if query
                    else "No customers yet. Use Customers → New Customer to add one."
                )
            else:
                status_label.config(text="")

        def clear():
            search_term.set("")
            refresh()
            search_entry.focus_set()

        def do_search():
            refresh()
            children = tree.get_children()
            if children:
                first = children[0]
                tree.focus_set()
                tree.selection_set(first)
                tree.focus(first)
                tree.see(first)

        def open_selected():
            selection = tree.selection()
            if not selection:
                messagebox.showinfo("No selection", "Please select a customer first.")
                return
            self.show_customer_form(customer_db.get_customer(int(selection[0])))

        tree.bind("<Double-1>", lambda e: open_selected())
        tree.bind("<Return>", lambda e: open_selected())
        refresh()

    def show_customer_form(self, customer=None):
        """Create/edit a customer."""
        self.current_view = "customer_form"
        self._clear_container()
        editing = customer is not None
        ttk.Label(
            self.container,
            text="Edit Customer" if editing else "New Customer",
            font=("Segoe UI", 20, "bold"),
        ).pack(anchor="w", pady=(0, 15))

        form = ttk.Frame(self.container)
        form.pack(anchor="w")
        entries = {}
        fields = [
            ("name", "Name"),
            ("account_number", "Account #"),
            ("contact", "Contact"),
            ("email", "Email"),
            ("phone", "Phone"),
        ]
        for row, (key, label) in enumerate(fields):
            ttk.Label(form, text=label + ":").grid(row=row, column=0, sticky="w", pady=5, padx=(0, 10))
            entry = ttk.Entry(form, width=40)
            entry.grid(row=row, column=1, pady=5)
            if editing:
                entry.insert(0, customer[key] or "")
            elif key == "account_number":
                # Autogenerated on save for new customers.
                entry.insert(0, "(auto-generated)")
                entry.configure(state="readonly")
            entries[key] = entry

        def save():
            data = {key: entry.get().strip() for key, entry in entries.items()}
            if not data["name"]:
                messagebox.showwarning("Missing name", "Please enter a customer name.")
                return
            if not editing:
                data["account_number"] = ""  # let the data layer generate it
            try:
                if editing:
                    customer_db.update_customer(
                        customer["id"], data["name"], data["account_number"],
                        data["contact"], data["email"], data["phone"],
                    )
                else:
                    customer_db.add_customer(
                        data["name"], data["account_number"],
                        data["contact"], data["email"], data["phone"],
                    )
            except customer_db.DuplicateNameError:
                messagebox.showerror(
                    "Duplicate name", f"A customer named '{data['name']}' already exists."
                )
                return
            messagebox.showinfo("Saved", f"Customer '{data['name']}' saved.")
            self.show_customers()

        def delete_current():
            if not editing:
                return
            if messagebox.askyesno("Delete customer", f"Delete '{customer['name']}'?"):
                customer_db.delete_customer(customer["id"])
                self.show_customers()

        btns = ttk.Frame(self.container)
        btns.pack(anchor="w", pady=(20, 0))
        cancel = self._discard_guard(self.show_customers)
        ttk.Button(btns, text="Save (Ctrl+S)", command=save).pack(side="left")
        ttk.Button(btns, text="Cancel (Esc)", command=cancel).pack(side="left", padx=(8, 0))
        if editing:
            ttk.Button(btns, text="Delete (Ctrl+D)", command=delete_current).pack(side="left", padx=(8, 0))
        self._bind_form_shortcuts(
            save=save, cancel=cancel,
            delete=delete_current if editing else None,
        )

        # Account section: balance + receipt actions (only for an existing customer).
        if editing:
            account = ttk.LabelFrame(self.container, text="Account", padding=10)
            account.pack(anchor="w", fill="x", pady=(20, 0))
            balance = receipt_db.customer_balance(customer["id"])
            ttk.Label(
                account,
                text=f"Balance owed by customer: {balance:,.2f}",
                font=("Segoe UI", 12, "bold"),
            ).pack(anchor="w")
            acc_btns = ttk.Frame(account)
            acc_btns.pack(anchor="w", pady=(8, 0))
            ttk.Button(
                acc_btns, text="Record Receipt",
                command=lambda: self.show_receipt_form(customer["id"]),
            ).pack(side="left")
            ttk.Button(
                acc_btns, text="View Receipts",
                command=lambda: self.show_receipts(customer["id"]),
            ).pack(side="left", padx=(8, 0))
            ttk.Button(
                acc_btns, text="View Sales",
                command=lambda: self.show_sales(prefill=customer["name"]),
            ).pack(side="left", padx=(8, 0))

    # ---------------------------------------------------------------------- Sales
