"""Customers data-access layer.

A customer has a unique name plus account number, address, postcode, email and
phone. Stored in the central app.db.
"""

import sqlite3

from core.database import get_connection


class DuplicateNameError(Exception):
    """Raised when a customer name collides with an existing one."""


def create_table():
    """Create the customers table (with a unique name index) if needed."""
    with get_connection() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS customers (
                id             INTEGER PRIMARY KEY AUTOINCREMENT,
                name           TEXT NOT NULL,
                account_number TEXT,
                address        TEXT,
                postcode       TEXT,
                email          TEXT,
                phone          TEXT
            )
            """
        )
        conn.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_customers_name "
            "ON customers(name COLLATE NOCASE)"
        )
        # Add the address/postcode columns to databases created before them.
        # (An older `contact` column may still exist; it is no longer used.)
        cols = {row["name"] for row in conn.execute("PRAGMA table_info(customers)")}
        for column in ("address", "postcode"):
            if column not in cols:
                conn.execute(f"ALTER TABLE customers ADD COLUMN {column} TEXT")


def add_customer(name, account_number="", address="", postcode="", email="", phone=""):
    """Insert a customer and return its id. Raises DuplicateNameError on clash.

    A blank account number is autogenerated from the new row id (e.g. 'C00001').
    """
    with get_connection() as conn:
        try:
            cursor = conn.execute(
                "INSERT INTO customers (name, account_number, address, postcode, email, phone) "
                "VALUES (?, ?, ?, ?, ?, ?)",
                (name, account_number, address, postcode, email, phone),
            )
        except sqlite3.IntegrityError as exc:
            raise DuplicateNameError(name) from exc
        customer_id = cursor.lastrowid
        if not account_number:
            conn.execute(
                "UPDATE customers SET account_number = ? WHERE id = ?",
                (f"C{customer_id:05d}", customer_id),
            )
        return customer_id


def update_customer(customer_id, name, account_number="", address="", postcode="", email="", phone=""):
    """Update a customer. Raises DuplicateNameError if the name clashes."""
    with get_connection() as conn:
        try:
            conn.execute(
                "UPDATE customers "
                "SET name = ?, account_number = ?, address = ?, postcode = ?, email = ?, phone = ? "
                "WHERE id = ?",
                (name, account_number, address, postcode, email, phone, customer_id),
            )
        except sqlite3.IntegrityError as exc:
            raise DuplicateNameError(name) from exc


def get_customer(customer_id):
    """Return a single customer row by id, or None."""
    with get_connection() as conn:
        return conn.execute(
            "SELECT id, name, account_number, address, postcode, email, phone "
            "FROM customers WHERE id = ?",
            (customer_id,),
        ).fetchone()


def get_all_customers():
    """Return all customers ordered by name."""
    with get_connection() as conn:
        return conn.execute(
            "SELECT id, name, account_number, address, postcode, email, phone "
            "FROM customers ORDER BY name COLLATE NOCASE"
        ).fetchall()


def delete_customer(customer_id):
    """Delete a customer by id."""
    with get_connection() as conn:
        conn.execute("DELETE FROM customers WHERE id = ?", (customer_id,))
