"""Sales data-access layer.

A sale belongs to a customer, has a status of 'Quote', 'Order' or 'Invoice', and
contains line items that are either a product or a service (each with quantity, a
net unit price and a VAT rate). Orders and Invoices reduce product stock and count
as owed by the customer (see products.py / receipts.py); Quotes are provisional.

Each status carries its own autogenerated number (Q…, O…, INV…). As a sale is
promoted (Quote → Order → Invoice) it keeps the numbers it earned at each status;
`reference` always mirrors the number of the sale's current status.
"""

import datetime

from core import daterange, money, posting
from core.database import get_connection

STATUSES = ("Quote", "Order", "Invoice", "Credit Note")
DEFAULT_VAT_RATE = 20.0

# Statuses that consume stock and are owed by the customer (Quotes are provisional).
OWED_STATUSES = ("Order", "Invoice")

# Per-status autogenerated numbering: display prefix and the column that stores it.
# A Credit Note (customer return/adjustment) is numbered SCN… and credits an invoice.
_STATUS_PREFIX = {"Quote": "Q", "Order": "O", "Invoice": "INV", "Credit Note": "SCN"}
_STATUS_COLUMN = {"Quote": "quote_no", "Order": "order_no", "Invoice": "invoice_no",
                  "Credit Note": "credit_no"}

# SQL fragments for line money, in whole PENCE (unqualified columns; `si.` variant
# for subqueries). VAT is rounded per line, half-up — CAST(ROUND(.. /100.0)) matches
# money.vat_pence exactly (verified over all rate/price/qty combinations).
_LINE_NET = "quantity * unit_price_pence"
_LINE_VAT = "CAST(ROUND(quantity * unit_price_pence * COALESCE(vat_rate, 20) / 100.0, 0) AS INTEGER)"
_LINE_GROSS = (
    "(quantity * unit_price_pence + "
    "CAST(ROUND(quantity * unit_price_pence * COALESCE(vat_rate, 20) / 100.0, 0) AS INTEGER))"
)
_SI_GROSS = (
    "(si.quantity * si.unit_price_pence + "
    "CAST(ROUND(si.quantity * si.unit_price_pence * COALESCE(si.vat_rate, 20) / 100.0, 0) AS INTEGER))"
)


def _now():
    return datetime.datetime.now().isoformat(timespec="seconds")


def create_table():
    """Create the sales and sale_items tables if needed."""
    with get_connection() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS sales (
                id          INTEGER PRIMARY KEY AUTOINCREMENT,
                customer_id INTEGER NOT NULL REFERENCES customers(id),
                status      TEXT NOT NULL,
                reference   TEXT,
                quote_no    TEXT,
                order_no    TEXT,
                invoice_no  TEXT,
                credit_no   TEXT,
                ref_invoice TEXT,                 -- credit note: the invoice number it credits
                vehicle_id  INTEGER REFERENCES vehicles(id),  -- optional linked vehicle
                date        TEXT,
                created_at  TEXT
            )
            """
        )
        # Add the per-status number columns to databases created before they existed.
        existing = {row["name"] for row in conn.execute("PRAGMA table_info(sales)")}
        for column in ("quote_no", "order_no", "invoice_no", "credit_no", "ref_invoice"):
            if column not in existing:
                conn.execute(f"ALTER TABLE sales ADD COLUMN {column} TEXT")
        # A sale may optionally be linked to a vehicle (VRM looked up under Vehicles).
        if "vehicle_id" not in existing:
            conn.execute("ALTER TABLE sales ADD COLUMN vehicle_id INTEGER REFERENCES vehicles(id)")
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS sale_items (
                id          INTEGER PRIMARY KEY AUTOINCREMENT,
                sale_id     INTEGER NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
                item_type   TEXT NOT NULL,                     -- 'product' or 'service'
                product_id  INTEGER REFERENCES products(id),
                service_id  INTEGER REFERENCES services(id),
                description TEXT,
                quantity    INTEGER NOT NULL,
                unit_price  REAL NOT NULL,                     -- pounds (display mirror)
                unit_price_pence INTEGER NOT NULL DEFAULT 0,   -- authoritative net unit price
                vat_rate    REAL NOT NULL DEFAULT 20
            )
            """
        )
        # Migrate sale_items created before the pence column existed (back-filled by
        # core.migrate_money from the REAL unit_price).
        si_cols = {row["name"] for row in conn.execute("PRAGMA table_info(sale_items)")}
        if "unit_price_pence" not in si_cols:
            conn.execute(
                "ALTER TABLE sale_items ADD COLUMN unit_price_pence INTEGER NOT NULL DEFAULT 0"
            )
        conn.execute("CREATE INDEX IF NOT EXISTS idx_sale_items_sale ON sale_items(sale_id)")
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_sale_items_product ON sale_items(product_id)"
        )


def _insert_items(conn, sale_id, items):
    conn.executemany(
        "INSERT INTO sale_items "
        "(sale_id, item_type, product_id, service_id, description, quantity, "
        " unit_price, unit_price_pence, vat_rate) "
        "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
        [
            (sale_id, it["item_type"], it.get("product_id"), it.get("service_id"),
             it.get("description", ""), it["quantity"], it["unit_price"],
             money.to_pence(it["unit_price"]), it.get("vat_rate", DEFAULT_VAT_RATE))
            for it in items
        ],
    )


def _next_number(conn, status):
    """Next autogenerated number for a status, e.g. 'Q0001' / 'O0007' / 'INV0042'.
    Sequences are independent per status."""
    prefix = _STATUS_PREFIX[status]
    column = _STATUS_COLUMN[status]
    highest = 0
    for row in conn.execute(
        f"SELECT {column} AS n FROM sales WHERE {column} IS NOT NULL"
    ):
        value = row["n"]
        digits = value[len(prefix):]
        if value.startswith(prefix) and digits.isdigit():
            highest = max(highest, int(digits))
    return f"{prefix}{highest + 1:04d}"


def _assign_number(conn, sale_id, status):
    """Ensure the sale has a number for `status` (generating one if not), and set
    `reference` to it. Re-saving at the same status keeps the existing number."""
    column = _STATUS_COLUMN[status]
    existing = conn.execute(
        f"SELECT {column} AS n FROM sales WHERE id = ?", (sale_id,)
    ).fetchone()["n"]
    number = existing or _next_number(conn, status)
    conn.execute(
        f"UPDATE sales SET {column} = ?, reference = ? WHERE id = ?",
        (number, number, sale_id),
    )
    return number


def create_sale(customer_id, status, date, items, ref_invoice=None, vehicle_id=None):
    """Insert a sale with its line items. Its number is autogenerated from the
    status. ``ref_invoice`` links a Credit Note to the invoice it credits;
    ``vehicle_id`` optionally links a looked-up vehicle. Returns the new sale id."""
    date = daterange.to_iso(date)
    with get_connection() as conn:
        cursor = conn.execute(
            "INSERT INTO sales (customer_id, status, ref_invoice, vehicle_id, date, created_at) "
            "VALUES (?, ?, ?, ?, ?, ?)",
            (customer_id, status, ref_invoice, vehicle_id, date, _now()),
        )
        sale_id = cursor.lastrowid
        _assign_number(conn, sale_id, status)
        _insert_items(conn, sale_id, items)
        posting.post_sale(conn, sale_id)
        return sale_id


def update_sale(sale_id, customer_id, status, date, items, ref_invoice=None,
                vehicle_id=None):
    """Update a sale, replacing all of its line items. A number is assigned for the
    new status if the sale doesn't already have one (numbers earned at earlier
    statuses are kept). ``vehicle_id`` optionally links a looked-up vehicle."""
    date = daterange.to_iso(date)
    with get_connection() as conn:
        conn.execute(
            "UPDATE sales SET customer_id = ?, status = ?, ref_invoice = ?, "
            "vehicle_id = ?, date = ? WHERE id = ?",
            (customer_id, status, ref_invoice, vehicle_id, date, sale_id),
        )
        _assign_number(conn, sale_id, status)
        conn.execute("DELETE FROM sale_items WHERE sale_id = ?", (sale_id,))
        _insert_items(conn, sale_id, items)
        posting.post_sale(conn, sale_id)


def delete_sale(sale_id):
    """Delete a sale (its line items cascade). Any ledger journal is reversed
    first, leaving the reversal as an audit trail."""
    with get_connection() as conn:
        posting.remove(conn, "sale", sale_id)
        conn.execute("DELETE FROM sales WHERE id = ?", (sale_id,))


def get_sale(sale_id):
    """Return the sale row (with customer name), or None."""
    with get_connection() as conn:
        return conn.execute(
            "SELECT s.id, s.customer_id, s.status, s.reference, "
            "s.quote_no, s.order_no, s.invoice_no, s.credit_no, s.ref_invoice, "
            "s.vehicle_id, s.date, c.name AS customer_name, "
            "v.vrm AS vehicle_vrm, v.make AS vehicle_make, v.model AS vehicle_model, "
            "v.build_year AS vehicle_year "
            "FROM sales s JOIN customers c ON c.id = s.customer_id "
            "LEFT JOIN vehicles v ON v.id = s.vehicle_id "
            "WHERE s.id = ?",
            (sale_id,),
        ).fetchone()


def get_sale_items(sale_id):
    """Return the line items for a sale."""
    with get_connection() as conn:
        return conn.execute(
            "SELECT id, item_type, product_id, service_id, description, quantity, "
            "unit_price, unit_price_pence, vat_rate FROM sale_items WHERE sale_id = ? ORDER BY id",
            (sale_id,),
        ).fetchall()


def sale_totals(sale_id):
    """Return {'net', 'vat', 'gross'} (pounds) for a sale."""
    return {k: money.from_pence(v) for k, v in sale_totals_pence(sale_id).items()}


def sale_totals_pence(sale_id):
    """Return {'net', 'vat', 'gross'} in whole pence for a sale (ledger primitive)."""
    with get_connection() as conn:
        row = conn.execute(
            f"SELECT COALESCE(SUM({_LINE_NET}), 0) AS net, "
            f"COALESCE(SUM({_LINE_VAT}), 0) AS vat, "
            f"COALESCE(SUM({_LINE_GROSS}), 0) AS gross "
            "FROM sale_items WHERE sale_id = ?",
            (sale_id,),
        ).fetchone()
        return {"net": row["net"], "vat": row["vat"], "gross": row["gross"]}


def customer_sales(customer_id, outstanding_only=False):
    """A customer's owed sales (Orders/Invoices) with total, allocated and
    outstanding amounts.

    Returns a list of dicts so the computed `outstanding` is available directly.
    """
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT s.id, s.reference, s.date, "
            f"COALESCE((SELECT SUM({_SI_GROSS}) FROM sale_items si "
            "          WHERE si.sale_id = s.id), 0) AS total, "
            "COALESCE((SELECT SUM(ra.amount_pence) FROM receipt_allocations ra "
            "          WHERE ra.sale_id = s.id), 0) AS allocated "
            "FROM sales s "
            "WHERE s.customer_id = ? AND s.status IN ('Order', 'Invoice') "
            "ORDER BY s.id",
            (customer_id,),
        ).fetchall()
    result = []
    for r in rows:
        outstanding_p = r["total"] - r["allocated"]   # whole pence
        if outstanding_only and outstanding_p <= 0:
            continue
        result.append({
            "id": r["id"], "reference": r["reference"], "date": r["date"],
            "total": money.from_pence(r["total"]),
            "allocated": money.from_pence(r["allocated"]),
            "outstanding": money.from_pence(outstanding_p),
        })
    return result


def list_for_customer(customer_id):
    """All sales for a customer (any status), newest first, with gross total."""
    with get_connection() as conn:
        return conn.execute(
            "SELECT s.id, s.reference, s.status, s.date, "
            f"COALESCE((SELECT SUM({_SI_GROSS}) FROM sale_items si "
            "          WHERE si.sale_id = s.id), 0) / 100.0 AS total "
            "FROM sales s WHERE s.customer_id = ? ORDER BY s.id DESC",
            (customer_id,),
        ).fetchall()


def list_for_vehicle(vehicle_id):
    """All sales linked to a vehicle (any status), newest first, with customer
    name and gross total."""
    with get_connection() as conn:
        return conn.execute(
            "SELECT s.id, s.reference, s.status, s.date, c.name AS customer_name, "
            f"COALESCE((SELECT SUM({_SI_GROSS}) FROM sale_items si "
            "          WHERE si.sale_id = s.id), 0) / 100.0 AS total "
            "FROM sales s JOIN customers c ON c.id = s.customer_id "
            "WHERE s.vehicle_id = ? ORDER BY s.id DESC",
            (vehicle_id,),
        ).fetchall()


def list_sales(text="", status=""):
    """List sales (with customer name and gross total) for the list view."""
    like = f"%{text}%"
    with get_connection() as conn:
        return conn.execute(
            "SELECT s.id, s.reference, s.status, s.date, s.customer_id, "
            "c.name AS customer_name, "
            f"COALESCE((SELECT SUM({_SI_GROSS}) FROM sale_items si "
            "          WHERE si.sale_id = s.id), 0) / 100.0 AS total "
            "FROM sales s JOIN customers c ON c.id = s.customer_id "
            "WHERE (s.reference LIKE ? COLLATE NOCASE OR c.name LIKE ? COLLATE NOCASE) "
            "AND (? = '' OR s.status = ?) "
            "ORDER BY s.id DESC",
            (like, like, status, status),
        ).fetchall()
